engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
          - mass_threshold: 20
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths: 
  - "www/lib/"
  - "hooks/"
  - "gulpfile.js"
  - "www/css/ionic.app.css"