image: filiosoft/ionic:python
variables:
  S3_BUCKET_NAME: "polr-mobile.filiosoft.net"
  BUILD_NUMBER: "0.1.$CI_BUILD_ID"
cache:
  paths:
  - node_modules/

dev-build-android:
  stage: build
  tags: 
    - docker
  before_script:
    - npm install
    - npm prune
    - python setcordovaversion.py $BUILD_NUMBER $CI_BUILD_ID config.xml
  script:
    - node node_modules/gulp/bin/gulp.js
  after_script:
    - mkdir apk
    - mv bin/Android/Release/android-release.apk Polr-Mobile-Dev-$BUILD_NUMBER.apk
  artifacts:
    paths:
    - Polr-Mobile-Dev-$BUILD_NUMBER.apk
  except:
    - tags

release-build-android:
  stage: build
  tags: 
    - docker
  before_script:
    - npm install
    - npm prune
    - python setcordovaversion.py $CI_BUILD_TAG $CI_BUILD_ID config.xml
  script:
    - node node_modules/gulp/bin/gulp.js
  after_script:
    - mkdir apk
    - mv bin/Android/Release/android-release.apk Polr-Mobile-Release-$CI_BUILD_TAG.apk
  artifacts:
    paths:
    - Polr-Mobile-Release-$CI_BUILD_TAG.apk
  only:
    - tags

lint:
  stage: test
  tags: 
    - docker
  before_script:
    - npm install
    - npm prune
  script:
    - node node_modules/gulp/bin/gulp.js test

deploy:
  image: python:latest
  stage: deploy
  tags: 
    - docker
  script:
  - pip install awscli
  - aws s3 cp ./ s3://$S3_BUCKET_NAME/ --recursive --exclude ".gitlab-ci.yml" --include "*"
  only:
  - gh-pages
  
mirror: 
  stage: deploy
  tags: 
    - docker
  script:
   - git clone --bare https://nprail:$GITLAB_ACCESS_KEY@gitlab.filiosoft.com/filiosoft-osp/polr-mobile.git
   - cd polr-mobile.git
   - git push --mirror https://nprail:$GITHUB_ACCESS_KEY@github.com/Filiosoft/polr-mobile.git