image: filiosoft/android-node:latest
variables:
  S3_BUCKET_NAME: "polr-mobile.filiosoft.net"
  VERSION_NUMBER: "0.1.$CI_BUILD_ID"
cache:
  paths:
  - node_modules/

dev-build-android:
  stage: build
  tags: 
    - docker
  before_script:
    - npm install
    - npm install -g scv-cli
    - npm prune
    - scv -n $VERSION_NUMBER -b $CI_BUILD_ID
  script:
    - node node_modules/gulp/bin/gulp.js
  after_script:
    - mkdir apk
    - mv bin/Android/Release/android-release.apk Polr-Mobile-Dev-$VERSION_NUMBER.apk
  artifacts:
    paths:
    - Polr-Mobile-Dev-$VERSION_NUMBER.apk
  except:
    - tags

release-build-android:
  stage: build
  tags: 
    - docker
  before_script:
    - npm install
    - npm install -g scv-cli
    - npm prune
    - scv -n $VERSION_NUMBER -b $CI_BUILD_ID
  script:
    - node node_modules/gulp/bin/gulp.js
  after_script:
    - mkdir apk
    - mv bin/Android/Release/android-release.apk Polr-Mobile-Release-$CI_BUILD_TAG.apk
  artifacts:
    paths:
    - Polr-Mobile-Release-$CI_BUILD_TAG.apk
  only:
    - tags

lint:
  stage: test
  tags: 
    - docker
  before_script:
    - npm install
    - npm prune
  script:
    - node node_modules/gulp/bin/gulp.js test

deploy:
  image: filiosoft/aws-cli:latest
  stage: deploy
  tags: 
    - docker
  script:
  - aws s3 cp ./ s3://$S3_BUCKET_NAME/ --recursive --exclude ".gitlab-ci.yml" --include "*"
  only:
  - gh-pages

pages:
  stage: deploy
  image: alpine:latest
  environment: pages
  tags:
    - docker
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - gh-pages
 
mirror: 
  stage: deploy
  tags: 
    - docker
  script:
   - git clone --bare https://nprail:$GITLAB_ACCESS_KEY@gitlab.filiosoft.com/oss/polr-mobile.git
   - cd polr-mobile.git
   - git push --mirror https://nprail:$GITHUB_ACCESS_KEY@github.com/Filiosoft/polr-mobile.git