image: registry.filiosoft.com/docker/android-node:latest
variables:
  S3_BUCKET_NAME: "polr-mobile.filiosoft.net"
  VERSION_NUMBER: "0.1.0"

build-android:
  stage: build
  environment: build/android
  tags:
    - docker
  before_script:
    - yarn install
  script:
    - npx gulp ci --vc $CI_PIPELINE_ID
    - npx gulp move-apk --vc $CI_PIPELINE_ID
  artifacts:
    paths:
    - bin/Android/Release/Polr-Mobile-Dev-*.apk

lint:
  stage: test
  tags:
    - docker
  before_script:
    - yarn install
  script:
    - node node_modules/gulp/bin/gulp.js test

deploy:
  image: filiosoft/aws-cli:latest
  stage: deploy
  tags:
    - docker
  script:
  - aws s3 cp ./ s3://$S3_BUCKET_NAME/ --recursive --exclude ".gitlab-ci.yml" --include "*"
  only:
  - gh-pages