sudo: true
language: android
cache:
  directories:
    - node_modules
android:
    components:
        - build-tools-23.0.1
        - android-23
        - platform-tools
        - tools
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-19
        - addon-google_apis-google-23

before_install:
  - nvm install v4
  - npm i -g npm@^2.0.0
  - npm install -g ionic@beta
  - npm install -g cordova
  - npm install -g gulp
install:
  - npm install
before_script:
  - npm prune
  - python setcordovaversion.py 0.1.$TRAVIS_BUILD_NUMBER $TRAVIS_BUILD_NUMBER config.xml
script:
  - gulp
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
