sudo: true
language: android
addons:
  artifacts:
    paths:
    - bin/**/*.apk
cache:
  directories:
    - node_modules
android:
    components:
        - build-tools-25.0.1
        - android-23
        - platform-tools
        - tools
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-19
        - addon-google_apis-google-23

before_install:
  - nvm install v6
  - npm i -g npm@^2.0.0
  - npm install -g ionic
  - npm install -g cordova
  - npm install -g gulp
  - npm install -g scv-cli
install:
  - npm install
before_script:
  - npm prune
  - scv -n 0.1.0 -b $TRAVIS_BUILD_NUMBER
script:
  - gulp
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
