language: android
addons:
  artifacts:
    paths:
    - bin/**/*.apk
cache:
  directories:
    - node_modules
jdk:
  - oraclejdk8
android:
    components:
        - build-tools-26.0.0
        - android-25
        - platform-tools
        - tools
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-19
        - addon-google_apis-google-23
        - addon-google_apis-google-24

before_install:
  - nvm install v6
  - curl -o- -L https://yarnpkg.com/install.sh | bash
install:
  - source ~/.bashrc
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
before_script:
  - node node_modules/scv-cli/scv.js -n 0.1.0 -b $TRAVIS_BUILD_NUMBER
script:
  - node node_modules/gulp/bin/gulp.js
after_script:
  - mv bin/Android/Release/android-release.apk bin/Android/Release/Polr-Mobile-Dev-0.1.0-$TRAVIS_BUILD_NUMBER.apk
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
